//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRetail_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int invoiceID { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public decimal totalAmount { get; set; }
        public decimal taxAmount { get; set; }
        public decimal shippingCost { get; set; }
        public int orderID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
