//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRetail_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentID { get; set; }
        public System.DateTime paymentDate { get; set; }
        public string paymentStatus { get; set; }
        public decimal amount { get; set; }
        public int orderID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
